
//EMPLOYEE POPUP TYPES
export const EMPLOYEE_POPUP_TYPE:string='EMPLOYEE'

//COMPANY POPUP TYPE
export const COMPANY_POPUP_TYPE:string='COMPANY'

//ACCOUNTING_PLAN POPUP TYPE
export const ACCOUNTING_PLAN_ROW_POPUP_TYPE:string='ACCOUNTING_PLAN_ROW'
export const ACCOUNTING_PLAN_POPUP_TYPE:string='ACCOUNTING_PLAN'


//TAX POPUP TYPE
export const TAX_POPUP_TYPE:string='TAX'

//CUSTOMER POPUP TYPE
export const CUSTOMER_POPUP_TYPE:string='CUSTOMER'

//SERVICES
export const SERVICES_POPUP_TYPE:string='SERVICES'

//PRODUCTS
export const PRODUCTS_POPUP_TYPE:string='PRODUCTS'

// SUPPLIERS
export const SUPPLIERS_POPUP_TYPE:string='SUPPLIERS'

//TRANSACTIONS
export const TRANSACTIONS_PRODUCTS_POPUP_TYPE:string='TRANSACTIONS-PRODUCTS'
export const TRANSACTIONS_SERVICES_POPUP_TYPE:string='TRANSACTIONS-SERVICES'
